---

- name: Sync codebase
  hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Server and project information
      debug:
        msg: "IP Address: {{ ansible_default_ipv4.address }}, Hostname: {{ ansible_hostname }}, Application Directory: {{ app_dir }}"

    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Copy requirements.txt
      copy:
        src: ../requirements.txt
        dest: "{{ app_dir }}/requirements.txt"

    - name: Install packages
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"

    - name: Sync codebase
      synchronize:
        src: ../src/
        dest: "{{ app_dir }}/src"
        rsync_opts:
          - "--exclude=__pycache__"
          - "--exclude=media"
          - "--exclude=db.sqlite3"

    - name: Daemon reload and restart gunicorn, nginx
      become: True
      shell: "{{ item }}"
      loop:
        - systemctl daemon-reload
        - systemctl restart gunicorn-{{ project_name }}
        - systemctl restart nginx